language: node_js

node_js:
  - "iojs"
  - "iojs-v1.0.4" 
  
env: 
  - TEST_SUITE=node
sudo: false
before_install: 
  - npm install -g mocha
  - npm install jscoverage --save-dev
  - npm install coveralls --save
  - npm install mocha-lcov-reporter --save
  - git submodule update --init --recursive
  
after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha test -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js