language: node_js
node_js:
  - "node"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
  
sudo: false
before_install: 
  - npm install -g mocha
  - npm install -g istanbul
  - npm install coveralls
  - git submodule update --init --recursive

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage