language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4" 
  
env: TEST_SUITE=node
sudo: false
before_install: 
  - npm install -g mocha
  - git submodule update --init --recursive

	  